# Generated by Django 4.1.5 on 2023-01-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_rename_listing_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='RentOrBuy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
