# Generated by Django 4.1.5 on 2023-01-07 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_blog_alter_property_options_property_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
        migrations.AlterModelOptions(
            name='topproperty',
            options={},
        ),
        migrations.RemoveField(
            model_name='property',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='topproperty',
            name='slug',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 7, 12, 3, 11, 151913)),
        ),
        migrations.AlterModelTable(
            name='property',
            table=None,
        ),
        migrations.AlterModelTable(
            name='topproperty',
            table=None,
        ),
    ]
