# Generated by Django 4.1.5 on 2023-01-08 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_allinone_contact_whoweare_alter_blog_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 14, 20, 39, 283087)),
        ),
    ]
