# Generated by Django 4.1.5 on 2023-01-11 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0007_alter_blog_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoweare',
            name='leadimg',
            field=models.ImageField(blank=True, default='myleadimg.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 16, 59, 48, 291047)),
        ),
    ]
