# Generated by Django 4.1.5 on 2023-02-09 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0008_whoweare_leadimg_alter_blog_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoweare',
            name='slug',
            field=models.SlugField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 9, 17, 7, 32, 894281)),
        ),
    ]
