# Generated by Django 4.1.5 on 2023-02-09 16:40

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0009_whoweare_slug_alter_blog_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('subtitle_1', models.CharField(max_length=500)),
                ('leadimg', models.ImageField(blank=True, default='myleadimg.jpg', null=True, upload_to='')),
                ('body', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, max_length=550, null=True)),
                ('published', models.BooleanField(default=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
                'db_table': 'About',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_1', models.CharField(max_length=200)),
                ('number_1', models.CharField(max_length=200)),
                ('start_2', models.CharField(max_length=200)),
                ('number_2', models.CharField(max_length=200)),
                ('start_3', models.CharField(max_length=200)),
                ('number_3', models.CharField(max_length=200)),
                ('start_4', models.CharField(max_length=200)),
                ('number_4', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Start',
                'verbose_name_plural': 'Start',
                'db_table': 'Start',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='whyus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('text_1', models.CharField(max_length=500)),
                ('text_2', models.CharField(max_length=500)),
                ('text_3', models.CharField(max_length=500)),
                ('text_4', models.CharField(max_length=500)),
                ('leadimg', models.ImageField(blank=True, default='myleadimg.jpg', null=True, upload_to='')),
                ('body', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, max_length=550, null=True)),
                ('published', models.BooleanField(default=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'whyus',
                'verbose_name_plural': 'whyus',
                'db_table': 'whyus',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 9, 17, 40, 52, 174207)),
        ),
    ]
