# Generated by Django 4.1.5 on 2023-02-11 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0010_about_start_whyus_alter_blog_date_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': True, 'verbose_name': 'Contacts', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_6',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_7',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_8',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_9',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 13, 55, 28, 289139)),
        ),
    ]
