# Generated by Django 4.1.5 on 2023-01-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='photo',
        ),
        migrations.AddField(
            model_name='realtor',
            name='realtorphoto',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d/'),
        ),
    ]
